
#pragma once

typedef enum {
	StrID_NONE, 
	StrID_Name,
	StrID_Description,
	STR_ID_BUTTON_SETUP_Param_Name,
    StrID_EffectDescription,
    STR_ID_MATH_TOPIC_SLIDER_Param_Name,
    STR_ID_MATH_SLIDER_ONE_Param_Name,
    STR_ID_MATH_SLIDER_TWO_Param_Name,
    STR_ID_MATH_SLIDER_THREE_Param_Name,
    STR_ID_MATH_SLIDER_FOUR_Param_Name,
    STR_ID_MATH_SLIDER_FIVE_Param_Name,
    STR_ID_MATH_SLIDER_SIX_Param_Name,
    STR_ID_MATH_SLIDER_SEVEN_Param_Name,
    STR_ID_MATH_SLIDER_HEIGHT_Param_Name,
    STR_ID_MATH_SLIDER_NINE_Param_Name,
    STR_ID_MATH_SLIDER_TEN_Param_Name,
    STR_ID_MATH_TOPIC_POINTS_Param_Name,
    STR_ID_MATH_POINT_ONE_Param_Name,
    STR_ID_MATH_POINT_TWO_Param_Name,
    STR_ID_MATH_POINT_THREE_Param_Name,
    STR_ID_MATH_POINT_FOUR_Param_Name,
    STR_ID_MATH_POINT_FIVE_Param_Name,
    STR_ID_MATH_POINT_SIX_Param_Name,
    STR_ID_MATH_POINT_SEVEN_Param_Name,
    STR_ID_MATH_POINT_HEIGHT_Param_Name,
    STR_ID_MATH_POINT_NINE_Param_Name,
    STR_ID_MATH_POINT_TEN_Param_Name,
    STR_ID_MATH_TOPIC_CB_Param_Name,
    STR_ID_MATH_CB_ONE_Param_Name,
    STR_ID_MATH_CB_TWO_Param_Name,
    STR_ID_MATH_CB_THREE_Param_Name,
    STR_ID_MATH_CB_FOUR_Param_Name,
    STR_ID_MATH_CB_FIVE_Param_Name,
    STR_ID_MATH_CB_SIX_Param_Name,
    STR_ID_MATH_CB_SEVEN_Param_Name,
    STR_ID_MATH_CB_HEIGHT_Param_Name,
    STR_ID_MATH_CB_NINE_Param_Name,
    STR_ID_MATH_CB_TEN_Param_Name,
    STR_ID_MATH_TOPIC_COLORS_Param_Name,
    STR_ID_MATH_COLOR_ONE_Param_Name,
    STR_ID_MATH_COLOR_TWO_Param_Name,
    STR_ID_MATH_COLOR_THREE_Param_Name,
    STR_ID_MATH_COLOR_FOUR_Param_Name,
    STR_ID_MATH_COLOR_FIVE_Param_Name,
    STR_ID_MATH_COLOR_SIX_Param_Name,
    STR_ID_MATH_COLOR_SEVEN_Param_Name,
    STR_ID_MATH_COLOR_HEIGHT_Param_Name,
    STR_ID_MATH_COLOR_NINE_Param_Name,
    STR_ID_MATH_COLOR_TEN_Param_Name,

	STR_ID_MATH_TOPIC_ROTS_Param_Name,
	STR_ID_MATH_ROT_ONE_Param_Name,
	STR_ID_MATH_ROT_TWO_Param_Name,
	STR_ID_MATH_ROT_THREE_Param_Name,
	STR_ID_MATH_ROT_FOUR_Param_Name,
	STR_ID_MATH_ROT_FIVE_Param_Name,
	STR_ID_MATH_ROT_SIX_Param_Name,
	STR_ID_MATH_ROT_SEVEN_Param_Name,
	STR_ID_MATH_ROT_HEIGHT_Param_Name,
	STR_ID_MATH_ROT_NINE_Param_Name,
	STR_ID_MATH_ROT_TEN_Param_Name,

    StrID_TOPIC_INPUTS_Param_Name,
    StrID_LAYER_ONE_Param_Name,
    StrID_TOFF_ONE_Param_Name,
    StrID_POFF_ONE_Param_Name,
	StrID_LAYER_TWO_Param_Name,
	StrID_TOFF_TWO_Param_Name,
	StrID_POFF_TWO_Param_Name,
	StrID_LAYER_THREE_Param_Name,
	StrID_TOFF_THREE_Param_Name,
	StrID_POFF_THREE_Param_Name,
	StrID_LAYER_FOUR_Param_Name,
	StrID_TOFF_FOUR_Param_Name,
	StrID_POFF_FOUR_Param_Name,

	StrID_CEP_GETARB_Param_Name,
    StrID_CEP_REturnMessage_Param_Name,
    StrID_VersionError,
    StrID_JSONError,
	StrID_NUMTYPES
} StrIDType;

